### ISSUE TITLE
Test YAML update script on DEV

### ISSUE THREAD

**Issue by rockivist** [YaleArchivesSpace/YAML#2]
@mark-cooper I've accepted your pull request and created branches for test and dev. Want to run a test update against DEV?

**Comment by mark-cooper** [comment]
@rockivist thanks, and yes! Will get to this asap next week.

**Comment by mark-cooper** [comment]
@rockivist this should kick in from next Monday. This means:

- We are deploying from this repo (YaleArchivesSpace/YAML)
- DEV uses the dev branch
- TEST uses the test branch
- PROD uses the master branch

Let us know via support if we need to look into anything!

**Comment by rockivist** [comment]
@mark-cooper Yes, that sounds good.

Confirm when you have the plugin in place and we'll find a reason to rest a YAML update.

**Comment by fordmadox** [comment]
@mark-cooper :  i've just updated our TEST branch.  since this is a plugin now, does that mean that we only need to include overrides in the YML files rather than the whole file?  that's what i've assumed, so when i added public/locales/en.yml, you'll see that I just added one thing that we'd like to override in our TEST PUI for the time being.  please let me know if I'm mistaken about that, and I can set things up differently in this branch.  

as an aside, i was quite surprised that i needed to change the search_sorting Identifier in the YML file in this case, rather than the Resource _public Identifier.  In any event, even after this is up on TEST, I imagine that we'll want to change the "/collection_organization" view via a separate plugin at some point.  Ideally, the inherited identifiers could display in this view (e.g. Call Number: GEN MSS 100. Series I), but since this view doesn't have access to the inherited information and instead displays the unitid by itself after the label (e.g. Call Number: 1), I'm sure that our staff will want to override that behavior so that it displays something more condensed and meaningful in this view, such as "Series 1", without a label.  Just an aside, since I noticed that changing the Identifier label as requested looks to have other side effects.

**Comment by mark-cooper** [comment]
@fordmadox "does that mean that we only need to include overrides in the YML files rather than the whole file?"

Yes, that's right, you only need to include the keys you specifically want to override.

"as an aside, i was quite surprised that i needed to change the search_sorting Identifier in the YML file in this case, rather than the Resource _public Identifier"

For us there have been a couple of cases where the string assembly for display in the pui has been counter-intuitive and difficult to override. Could use some review.
